name = "macropad_bsp"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

[[depends-on]]
rp2040_hal = "^1.5.0"

# GD25Q64C - 64 Mbit (8 MB) QSPI flash
# http://www.elm-tech.com/ja/products/spi-flash-memory/gd25q64/gd25q64.pdf
[configuration.values]
rp2040_hal.Flash_Chip = "generic_qspi"
